import type { Language, PracticeMode } from '@/types'

const ENGLISH_LOWERCASE = 'abcdefghijklmnopqrstuvwxyz'.split('')
const ENGLISH_UPPERCASE = 'ABCDEFGHIJKLMNOPQRSTUVWXYZ'.split('')
const RUSSIAN_LOWERCASE = 'абвгдеёжзийклмнопрстуфхцчшщъыьэюя'.split('')
const RUSSIAN_UPPERCASE = 'АБВГДЕЁЖЗИЙКЛМНОПРСТУФХЦЧШЩЪЫЬЭЮЯ'.split('')
const NUMBERS = '0123456789'.split('')
const SPECIAL_CHARS = '!@#$%^&*()_+-=[]{}|;:\'",.<>?/`~'.split('')

const ENGLISH_BIGRAMS = [
  'th',
  'he',
  'in',
  'er',
  'an',
  're',
  'on',
  'at',
  'en',
  'nd',
  'ti',
  'es',
  'or',
  'te',
  'of',
  'ed',
  'is',
  'it',
  'al',
  'ar',
  'st',
  'to',
  'nt',
  'ng',
  'se',
  'ha',
  'as',
  'ou',
  'io',
  'le',
  've',
  'co',
  'me',
  'de',
  'hi',
  'ri',
  'ro',
  'ic',
  'ne',
  'ea',
  'ra',
  'ce',
  'li',
  'ch',
  'll',
  'be',
  'ma',
  'si',
  'om',
  'ur',
  'ca',
  'el',
  'ta',
  'la',
  'ns',
  'di',
  'fo',
  'ho',
  'pe',
  'ec',
  'pr',
  'no',
  'ct',
  'us',
  'ac',
  'ot',
  'il',
  'tr',
  'ly',
  'wa',
  'we',
  'wi',
  'wh',
  'mo',
  'lo',
  'ke',
  'gh',
  'av',
  'sh',
  'ss',
  'rs',
  'rt',
  'ld',
  'po',
  'pl',
  'oo',
  'ee',
  'ff',
  'ck',
  'up',
]

const ENGLISH_TRIGRAMS = [
  'the',
  'and',
  'ing',
  'ion',
  'tio',
  'ent',
  'ati',
  'for',
  'her',
  'ter',
  'tha',
  'ere',
  'hat',
  'his',
  'con',
  'res',
  'ver',
  'all',
  'ons',
  'nce',
  'men',
  'ith',
  'ted',
  'ers',
  'pro',
  'thi',
  'wit',
  'are',
  'ess',
  'not',
  'ive',
  'was',
  'ect',
  'rea',
  'com',
  'eve',
  'per',
  'int',
  'est',
  'sta',
  'cti',
  'ica',
  'ist',
  'ear',
  'ain',
  'one',
  'our',
  'iti',
  'you',
  'oth',
  'out',
  'had',
  'she',
  'him',
  'has',
  'wer',
  'but',
  'who',
  'how',
  'can',
  'ill',
  'ght',
  'oul',
  'uld',
  'ave',
  'ore',
  'any',
  'use',
  'new',
  'day',
  'man',
  'get',
  'say',
  'now',
  'see',
  'too',
  'may',
  'way',
  'old',
  'end',
]

const ENGLISH_TETRAGRAMS = [
  'tion',
  'nthe',
  'ther',
  'that',
  'ofth',
  'fthe',
  'thes',
  'with',
  'inth',
  'atio',
  'othe',
  'them',
  'andt',
  'tand',
  'ethe',
  'ting',
  'ment',
  'ions',
  'this',
  'here',
  'from',
  'ould',
  'have',
  'ight',
  'were',
  'ever',
  'thou',
  'your',
  'they',
  'thei',
  'hich',
  'whic',
  'ence',
  'ough',
  'ance',
  'ious',
  'able',
  'ness',
  'will',
  'what',
  'when',
  'some',
  'time',
  'over',
  'then',
  'than',
  'into',
  'only',
  'also',
  'back',
  'make',
  'good',
  'know',
  'take',
  'give',
  'work',
  'life',
  'year',
  'said',
  'most',
  'more',
  'many',
  'such',
  'long',
  'hand',
  'part',
  'same',
  'much',
  'just',
  'like',
  'come',
  'look',
  'want',
  'help',
  'best',
  'even',
  'form',
  'case',
  'each',
  'need',
  'feel',
  'made',
  'used',
  'data',
  'word',
  'home',
  'late',
  'self',
  'righ',
  'true',
]

const ENGLISH_PENTAGRAMS = [
  'ation',
  'tions',
  'which',
  'there',
  'their',
  'other',
  'about',
  'would',
  'these',
  'thing',
  'could',
  'after',
  'under',
  'where',
  'every',
  'first',
  'world',
  'still',
  'never',
  'those',
  'right',
  'being',
  'house',
  'again',
  'great',
  'since',
  'order',
  'point',
  'found',
  'place',
  'state',
  'three',
  'years',
  'while',
  'later',
  'think',
  'might',
  'shall',
  'small',
  'large',
  'often',
  'today',
  'above',
  'below',
  'water',
  'power',
  'money',
  'human',
  'paper',
  'party',
  'story',
  'light',
  'stand',
  'short',
  'along',
  'begin',
  'women',
  'child',
  'group',
  'level',
  'local',
  'until',
  'young',
  'least',
  'voice',
  'times',
  'games',
  'music',
  'study',
  'words',
  'ideas',
  'kinds',
  'makes',
  'comes',
  'looks',
  'needs',
  'given',
  'taken',
  'asked',
  'shown',
  'using',
  'based',
  'basic',
  'legal',
  'clear',
  'early',
  'known',
  'added',
  'start',
  'ended',
]

const ENGLISH_HEXAGRAMS = [
  'ations',
  'tional',
  'nation',
  'cation',
  'lation',
  'ention',
  'sation',
  'mation',
  'ration',
  'having',
  'making',
  'coming',
  'should',
  'before',
  'though',
  'people',
  'within',
  'during',
  'little',
  'system',
  'public',
  'always',
  'almost',
  'around',
  'really',
  'change',
  'second',
  'states',
  'family',
  'school',
  'number',
  'member',
  'others',
  'better',
  'rather',
  'future',
  'recent',
  'design',
  'action',
  'strong',
  'return',
  'common',
  'ground',
  'center',
  'across',
  'answer',
  'reason',
  'either',
  'follow',
  'appear',
  'become',
  'became',
  'remain',
  'matter',
  'longer',
  'likely',
  'mostly',
  'friend',
  'nature',
  'create',
  'effect',
  'result',
  'market',
  'health',
  'social',
  'global',
  'growth',
  'review',
  'course',
  'method',
  'energy',
  'minute',
  'moment',
  'window',
  'search',
  'access',
  'format',
  'status',
  'choice',
  'expect',
  'except',
  'figure',
  'detail',
  'target',
  'random',
]

const RUSSIAN_BIGRAMS = [
  'ст',
  'но',
  'то',
  'на',
  'ен',
  'ко',
  'не',
  'ет',
  'ов',
  'ро',
  'ра',
  'во',
  'по',
  'ли',
  'ни',
  'ер',
  'го',
  'ре',
  'ор',
  'ол',
  'ос',
  'ом',
  'ть',
  'от',
  'ан',
  'ло',
  'те',
  'пр',
  'ка',
  'ал',
  'де',
  'ел',
  'ль',
  'та',
  'ва',
  'ве',
  'из',
  'да',
  'же',
  'ед',
  'ны',
  'за',
  'им',
  'ся',
  'ск',
  'ый',
  'ое',
  'ий',
  'ви',
  'об',
  'мо',
  'ми',
  'тр',
  'чи',
  'сл',
  'од',
  'до',
  'вы',
  'су',
  'ру',
  'ше',
  'ша',
  'ча',
  'че',
  'бы',
  'бу',
  'бо',
  'бе',
  'ну',
  'со',
  'оп',
  'ар',
  'ри',
  'ла',
  'ок',
  'пе',
  'ич',
  'сп',
  'ма',
  'ме',
]

const RUSSIAN_TRIGRAMS = [
  'сто',
  'ста',
  'ени',
  'ого',
  'его',
  'ово',
  'что',
  'про',
  'при',
  'ост',
  'ние',
  'ере',
  'ров',
  'ель',
  'ром',
  'оро',
  'ком',
  'тел',
  'ном',
  'пол',
  'ала',
  'ной',
  'ред',
  'ани',
  'ело',
  'ено',
  'ков',
  'ств',
  'ова',
  'али',
  'пер',
  'под',
  'так',
  'как',
  'это',
  'буд',
  'для',
  'или',
  'она',
  'они',
  'все',
  'нет',
  'там',
  'где',
  'раз',
  'над',
  'без',
  'них',
  'ему',
  'вам',
  'мен',
  'дел',
  'сво',
  'пос',
  'пот',
  'мож',
  'стр',
  'кто',
  'был',
  'вот',
  'уже',
  'зна',
  'сам',
  'еще',
  'гос',
  'год',
  'вре',
  'жиз',
  'люд',
  'сей',
  'каж',
  'тог',
  'сле',
  'нов',
  'вид',
  'меж',
  'пор',
  'вто',
  'тре',
  'вла',
]

const RUSSIAN_TETRAGRAMS = [
  'ение',
  'ания',
  'ство',
  'ости',
  'ного',
  'того',
  'тель',
  'кото',
  'пере',
  'пред',
  'толь',
  'такж',
  'кажд',
  'чтоб',
  'нужн',
  'можн',
  'може',
  'буде',
  'было',
  'врем',
  'сего',
  'свои',
  'своё',
  'люде',
  'людь',
  'стра',
  'росс',
  'рост',
  'пото',
  'посл',
  'перв',
  'втор',
  'трет',
  'один',
  'одна',
  'когд',
  'тогд',
  'года',
  'году',
  'лето',
  'здес',
  'сейч',
  'сист',
  'форм',
  'данн',
  'полн',
  'долж',
  'имен',
  'сдел',
  'дела',
  'дело',
  'деле',
  'коне',
  'конц',
  'нача',
  'начн',
  'обра',
  'сказ',
  'случ',
  'книж',
  'прав',
  'друг',
  'межд',
  'пост',
  'прои',
  'проц',
  'испо',
  'вида',
  'мног',
  'тоже',
  'лишь',
  'сраз',
  'если',
  'себе',
  'утро',
  'путь',
  'обще',
  'даль',
  'сама',
  'само',
]

const RUSSIAN_PENTAGRAMS = [
  'котор',
  'после',
  'между',
  'перед',
  'время',
  'также',
  'новый',
  'новые',
  'может',
  'очень',
  'нужно',
  'чтобы',
  'таких',
  'своей',
  'своих',
  'своим',
  'людей',
  'стать',
  'годов',
  'жизни',
  'место',
  'любой',
  'потом',
  'будет',
  'можно',
  'будто',
  'снова',
  'всего',
  'когда',
  'тогда',
  'сдела',
  'делал',
  'делае',
  'сказа',
  'самый',
  'более',
  'много',
  'каждо',
  'пятью',
  'вновь',
  'среди',
  'будем',
  'будут',
  'одним',
  'одной',
  'одних',
  'миром',
  'связь',
  'слово',
  'слова',
  'страх',
  'страш',
  'народ',
  'людям',
  'детей',
  'земли',
  'глаза',
  'сердц',
  'мысли',
  'делам',
  'делах',
  'делом',
  'точно',
  'сразу',
  'почти',
  'вмест',
  'новая',
  'новое',
  'вчера',
  'сегод',
  'войти',
  'вышел',
  'знает',
  'знать',
  'книги',
  'город',
  'войны',
  'помню',
  'любит',
  'тольк',
]

const RUSSIAN_HEXAGRAMS = [
  'которы',
  'только',
  'потому',
  'должен',
  'первый',
  'второй',
  'третий',
  'сейчас',
  'всегда',
  'можете',
  'каждое',
  'людьми',
  'вместе',
  'страна',
  'страны',
  'начало',
  'работа',
  'времен',
  'любого',
  'данных',
  'однако',
  'именно',
  'ничего',
  'многих',
  'почему',
  'откуда',
  'раньше',
  'будете',
  'своего',
  'своими',
  'своему',
  'самого',
  'нового',
  'новыми',
  'новост',
  'сделал',
  'сделан',
  'сказал',
  'вопрос',
  'ответы',
  'помочь',
  'других',
  'должна',
  'должны',
  'стране',
  'работы',
  'работу',
  'многие',
  'другой',
  'другие',
  'каждый',
  'первом',
  'втором',
  'третье',
  'вместо',
  'совсем',
  'большо',
  'меньше',
  'деньги',
  'города',
  'городе',
  'власть',
  'систем',
  'област',
  'госуда',
  'общест',
  'планов',
  'рынках',
  'истина',
  'страха',
  'делать',
  'делает',
  'делают',
  'можешь',
  'сказки',
  'важный',
  'разные',
  'решить',
  'решени',
  'помощь',
]

export function getCharacterSet(language: Language, modes: PracticeMode[]): string[] {
  const chars: string[] = []
  const isEnglish = language === 'english'

  for (const mode of modes) {
    switch (mode) {
      case 'lowercase':
        chars.push(...(isEnglish ? ENGLISH_LOWERCASE : RUSSIAN_LOWERCASE))
        break
      case 'uppercase':
        chars.push(...(isEnglish ? ENGLISH_UPPERCASE : RUSSIAN_UPPERCASE))
        break
      case 'numbers':
        chars.push(...NUMBERS)
        break
      case 'special':
        chars.push(...SPECIAL_CHARS)
        break
      case 'bigrams':
        chars.push(...(isEnglish ? ENGLISH_BIGRAMS : RUSSIAN_BIGRAMS))
        break
      case 'trigrams':
        chars.push(...(isEnglish ? ENGLISH_TRIGRAMS : RUSSIAN_TRIGRAMS))
        break
      case 'tetragrams':
        chars.push(...(isEnglish ? ENGLISH_TETRAGRAMS : RUSSIAN_TETRAGRAMS))
        break
      case 'pentagrams':
        chars.push(...(isEnglish ? ENGLISH_PENTAGRAMS : RUSSIAN_PENTAGRAMS))
        break
      case 'hexagrams':
        chars.push(...(isEnglish ? ENGLISH_HEXAGRAMS : RUSSIAN_HEXAGRAMS))
        break
      case 'text':
        return [generatePseudoText(language)]
    }
  }

  return chars.length > 0 ? chars : isEnglish ? ENGLISH_LOWERCASE : RUSSIAN_LOWERCASE
}

function generatePseudoWord(language: Language): string {
  const trigrams = language === 'english' ? ENGLISH_TRIGRAMS : RUSSIAN_TRIGRAMS
  const bigrams = language === 'english' ? ENGLISH_BIGRAMS : RUSSIAN_BIGRAMS

  const wordLength = 4 + Math.floor(Math.random() * 5)
  let word = trigrams[Math.floor(Math.random() * trigrams.length)] ?? ''

  while (word.length < wordLength) {
    const lastTwo = word.slice(-2)
    const matchingBigrams = bigrams.filter((b) => b[0] === lastTwo[1])
    if (matchingBigrams.length > 0) {
      const next = matchingBigrams[Math.floor(Math.random() * matchingBigrams.length)]
      word += next?.[1] ?? ''
    } else {
      const randomBigram = bigrams[Math.floor(Math.random() * bigrams.length)]
      word += randomBigram?.[1] ?? ''
    }
  }

  return word.slice(0, wordLength)
}

export function generatePseudoText(language: Language, wordCount = 8): string {
  const words: string[] = []
  for (let i = 0; i < wordCount; i++) {
    words.push(generatePseudoWord(language))
  }
  return words.join(' ')
}

export function findKeyCode(char: string, language: Language): string | null {
  const layouts =
    language === 'english'
      ? [
          { code: 'KeyQ', keys: ['q', 'Q'] },
          { code: 'KeyW', keys: ['w', 'W'] },
          { code: 'KeyE', keys: ['e', 'E'] },
          { code: 'KeyR', keys: ['r', 'R'] },
          { code: 'KeyT', keys: ['t', 'T'] },
          { code: 'KeyY', keys: ['y', 'Y'] },
          { code: 'KeyU', keys: ['u', 'U'] },
          { code: 'KeyI', keys: ['i', 'I'] },
          { code: 'KeyO', keys: ['o', 'O'] },
          { code: 'KeyP', keys: ['p', 'P'] },
          { code: 'KeyA', keys: ['a', 'A'] },
          { code: 'KeyS', keys: ['s', 'S'] },
          { code: 'KeyD', keys: ['d', 'D'] },
          { code: 'KeyF', keys: ['f', 'F'] },
          { code: 'KeyG', keys: ['g', 'G'] },
          { code: 'KeyH', keys: ['h', 'H'] },
          { code: 'KeyJ', keys: ['j', 'J'] },
          { code: 'KeyK', keys: ['k', 'K'] },
          { code: 'KeyL', keys: ['l', 'L'] },
          { code: 'KeyZ', keys: ['z', 'Z'] },
          { code: 'KeyX', keys: ['x', 'X'] },
          { code: 'KeyC', keys: ['c', 'C'] },
          { code: 'KeyV', keys: ['v', 'V'] },
          { code: 'KeyB', keys: ['b', 'B'] },
          { code: 'KeyN', keys: ['n', 'N'] },
          { code: 'KeyM', keys: ['m', 'M'] },
          { code: 'Digit1', keys: ['1', '!'] },
          { code: 'Digit2', keys: ['2', '@'] },
          { code: 'Digit3', keys: ['3', '#'] },
          { code: 'Digit4', keys: ['4', '$'] },
          { code: 'Digit5', keys: ['5', '%'] },
          { code: 'Digit6', keys: ['6', '^'] },
          { code: 'Digit7', keys: ['7', '&'] },
          { code: 'Digit8', keys: ['8', '*'] },
          { code: 'Digit9', keys: ['9', '('] },
          { code: 'Digit0', keys: ['0', ')'] },
          { code: 'Space', keys: [' '] },
        ]
      : [
          { code: 'Backquote', keys: ['ё', 'Ё'] },
          { code: 'KeyQ', keys: ['й', 'Й'] },
          { code: 'KeyW', keys: ['ц', 'Ц'] },
          { code: 'KeyE', keys: ['у', 'У'] },
          { code: 'KeyR', keys: ['к', 'К'] },
          { code: 'KeyT', keys: ['е', 'Е'] },
          { code: 'KeyY', keys: ['н', 'Н'] },
          { code: 'KeyU', keys: ['г', 'Г'] },
          { code: 'KeyI', keys: ['ш', 'Ш'] },
          { code: 'KeyO', keys: ['щ', 'Щ'] },
          { code: 'KeyP', keys: ['з', 'З'] },
          { code: 'BracketLeft', keys: ['х', 'Х'] },
          { code: 'BracketRight', keys: ['ъ', 'Ъ'] },
          { code: 'KeyA', keys: ['ф', 'Ф'] },
          { code: 'KeyS', keys: ['ы', 'Ы'] },
          { code: 'KeyD', keys: ['в', 'В'] },
          { code: 'KeyF', keys: ['а', 'А'] },
          { code: 'KeyG', keys: ['п', 'П'] },
          { code: 'KeyH', keys: ['р', 'Р'] },
          { code: 'KeyJ', keys: ['о', 'О'] },
          { code: 'KeyK', keys: ['л', 'Л'] },
          { code: 'KeyL', keys: ['д', 'Д'] },
          { code: 'Semicolon', keys: ['ж', 'Ж'] },
          { code: 'Quote', keys: ['э', 'Э'] },
          { code: 'KeyZ', keys: ['я', 'Я'] },
          { code: 'KeyX', keys: ['ч', 'Ч'] },
          { code: 'KeyC', keys: ['с', 'С'] },
          { code: 'KeyV', keys: ['м', 'М'] },
          { code: 'KeyB', keys: ['и', 'И'] },
          { code: 'KeyN', keys: ['т', 'Т'] },
          { code: 'KeyM', keys: ['ь', 'Ь'] },
          { code: 'Comma', keys: ['б', 'Б'] },
          { code: 'Period', keys: ['ю', 'Ю'] },
          { code: 'Digit1', keys: ['1', '!'] },
          { code: 'Digit2', keys: ['2', '"'] },
          { code: 'Digit3', keys: ['3', '№'] },
          { code: 'Digit4', keys: ['4', ';'] },
          { code: 'Digit5', keys: ['5', '%'] },
          { code: 'Digit6', keys: ['6', ':'] },
          { code: 'Digit7', keys: ['7', '?'] },
          { code: 'Digit8', keys: ['8', '*'] },
          { code: 'Digit9', keys: ['9', '('] },
          { code: 'Digit0', keys: ['0', ')'] },
          { code: 'Space', keys: [' '] },
        ]

  for (const { code, keys } of layouts) {
    if (keys.includes(char)) return code
  }
  return null
}

export function requiresShift(char: string): boolean {
  return /[A-ZА-ЯЁ!@#$%^&*()_+{}|:"<>?~]/.test(char)
}
