name: Deploy Application

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build and Deploy using docker-nginx-vps-deploy-action
        id: deploy-action
        uses: nikolay-e/docker-nginx-vps-deploy-action@main
        with:
          image-name: 'touch-typing-com'
          docker-context: '.'
          docker-file: 'Dockerfile'
          container-port: '8446'
          domain: 'touch-typing.nikolay-eremeev.com'

          docker-registry-username: ${{ secrets.DOCKER_REGISTRY_USERNAME }}
          vps-host: ${{ secrets.VPS_HOST }}
          vps-user: ${{ secrets.VPS_USER }}
          container-internal-port: '80'
        env:
          DOCKER_REGISTRY_TOKEN: ${{ secrets.DOCKER_REGISTRY_TOKEN }}
          VPS_SSH_PRIVATE_KEY: ${{ secrets.VPS_SSH_PRIVATE_KEY }}
          SSL_CERT: ${{ secrets.SSL_CERT }}
          SSL_KEY: ${{ secrets.SSL_KEY }}

      - name: Print Deployment Info
        if: always()
        run: |
          echo "Action execution finished."
          echo "Image Tag: ${{ steps.deploy-action.outputs.image-tag }}"
          echo "Image URL: ${{ steps.deploy-action.outputs.image-url }}"
          echo "Deployment URL: ${{ steps.deploy-action.outputs.deployment-url }}"