name: Build and Deploy Web Site

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    name: Build and Deploy Web Site
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build and Deploy using docker-nginx-vps-deploy-action
        id: deploy
        uses: nikolay-e/docker-nginx-vps-deploy-action@main
        with:
          container-port: 8446
          docker-context: .
          docker-file: Dockerfile
          docker-registry-token: ${{ secrets.DOCKER_REGISTRY_TOKEN }}
          docker-registry-username: ${{ secrets.DOCKER_REGISTRY_USERNAME }}
          domain: 'touch-typing.nikolay-eremeev.com'
          image-name: 'touch-typing-com'
          ssl-cert: ${{ secrets.SSL_CERT }}
          ssl-key: ${{ secrets.SSL_KEY }}
          vps-host: ${{ secrets.VPS_HOST }}
          vps-ssh-private-key: ${{ secrets.VPS_SSH_PRIVATE_KEY }}
          vps-user: ${{ secrets.VPS_USER }}
