name: Deploy with Helm

on:
  push:
    branches: [ main ]
  workflow_dispatch:

env:
  IMAGE_NAME: touch-typing

jobs:
  build-and-deploy:
    name: Build and Deploy to K8s
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_REGISTRY_USERNAME }}
          password: ${{ secrets.DOCKER_REGISTRY_TOKEN }}

      - name: Extract metadata
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ secrets.DOCKER_REGISTRY_USERNAME }}/${{ env.IMAGE_NAME }}
          tags: |
            type=ref,event=branch
            type=ref,event=pr
            type=sha,prefix={{branch}}-
            type=raw,value=latest,enable={{is_default_branch}}

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          cache-from: type=registry,ref=${{ secrets.DOCKER_REGISTRY_USERNAME }}/${{ env.IMAGE_NAME }}:buildcache
          cache-to: type=registry,ref=${{ secrets.DOCKER_REGISTRY_USERNAME }}/${{ env.IMAGE_NAME }}:buildcache,mode=max

      - name: Install kubectl
        uses: azure/setup-kubectl@v3
        with:
          version: 'latest'

      - name: Install Helm
        uses: azure/setup-helm@v3
        with:
          version: 'latest'

      - name: Configure kubectl
        run: |
          mkdir -p $HOME/.kube
          echo "${{ secrets.KUBE_CONFIG }}" | base64 --decode > $HOME/.kube/config
          chmod 600 $HOME/.kube/config
        env:
          KUBE_CONFIG: ${{ secrets.KUBE_CONFIG }}

      - name: Deploy with Helm
        run: |
          # Get the SHA tag from the metadata
          SHA_TAG=$(echo "${{ steps.meta.outputs.tags }}" | grep -E "main-[a-f0-9]+" | head -1 | cut -d: -f2)
          
          helm upgrade --install touch-typing ./helm/touch-typing \
            --namespace touch-typing \
            --create-namespace \
            --set image.repository=${{ secrets.DOCKER_REGISTRY_USERNAME }}/${{ env.IMAGE_NAME }} \
            --set image.tag=${SHA_TAG} \
            --wait \
            --timeout 5m

      - name: Verify deployment
        run: |
          kubectl -n touch-typing rollout status deployment/touch-typing
          kubectl -n touch-typing get pods
          kubectl -n touch-typing get ingress